name: Build Serilog.Sinks.MFilesObject

on:
  workflow_dispatch:
  push:
    branches: [ master, main, develop, release/*, prerelease/*, feature/* ]
    paths: ["src/**"]

jobs:
  build:
    timeout-minutes: 10
    runs-on: 'windows-2019'

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6

    - name: Set timezone on Windows to Central Europe Standard Time
      run: tzutil /s "Central Europe Standard Time"

    - name: Restore NuGet packages
      run: nuget restore Serilog.Sinks.MFilesObject.sln

#    - name: Build solution - DEBUG configuration
#      run: msbuild Serilog.Sinks.MFilesObject.sln /nologo /verbosity:m /p:Configuration=Debug /t:Build /p:DefineConstants="DONOTDEPLOY"

    - name: Build solution - RELEASE configuration
      run: msbuild Serilog.Sinks.MFilesObject.sln /nologo /verbosity:m /p:Configuration=Release /t:Build /p:DefineConstants="DONOTDEPLOY"
